// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiUhpmdw7ZJFm1U2TdttBhN-Rla5akFF8',
    appId: '1:1052831909854:web:e6e62fbd110dd4fa31ff4f',
    messagingSenderId: '1052831909854',
    projectId: 'uw-gis-project',
    authDomain: 'uw-gis-project.firebaseapp.com',
    storageBucket: 'uw-gis-project.appspot.com',
    measurementId: 'G-Z5NG68STSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpaA0RyF5995-o3_7X73EsBMW9LqbJ3Bg',
    appId: '1:1052831909854:android:c4fbd184b769d02731ff4f',
    messagingSenderId: '1052831909854',
    projectId: 'uw-gis-project',
    storageBucket: 'uw-gis-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS3FTcyLlyanbIc54BMaVJnl8bBV2Qyeo',
    appId: '1:1052831909854:ios:b653dd0719e5602731ff4f',
    messagingSenderId: '1052831909854',
    projectId: 'uw-gis-project',
    storageBucket: 'uw-gis-project.appspot.com',
    iosClientId: '1052831909854-pcq5tclf8nrn89o0i427pmcl8282g5m8.apps.googleusercontent.com',
    iosBundleId: 'com.testing.gisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS3FTcyLlyanbIc54BMaVJnl8bBV2Qyeo',
    appId: '1:1052831909854:ios:3c5ee8329e8eecd731ff4f',
    messagingSenderId: '1052831909854',
    projectId: 'uw-gis-project',
    storageBucket: 'uw-gis-project.appspot.com',
    iosClientId: '1052831909854-lbggvmi89t4gld98h0uls2eccq5nkjhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gisApp',
  );
}
